### PR TITLE
Static version

### PR DESCRIPTION
**Pull request by MrZoule**
My first pull request ever.
From France with love, managed by @DirtyF.
Sushis are getting hot, see you

### CODE REVIEW

**Comment by MrZoule** [comment]
By the way /support becomes /support.html

**Comment by rchavik** [comment]
Thanks.

I'm still pondering whether we should go fully static or not.  If we do, we start up a new repo from your commit.

**Comment by DirtyF** [comment]
why don't use github pages ?

**Comment by rchavik** [comment]
If we go static, we certainly could.  However, croogo is a 'cms' project, and I think we should try use own stuff.

**Comment by DirtyF** [comment]
indeed It would totally make sense.

**Comment by fahad19** [comment]
I would personally like it if Croogo went static for both the main domain, and blog. it would make contributions more easier.

**Comment by DirtyF** [comment]
If the only question is : do we really need a CMS to handle a webpage
and a blog (even if it's Croogo's), I think I would go with Fahad because AFAIAC I like the simplicity of editing a markdown file on Github and submitting a PR ;)

Now if you want to show off what Croogo can do, I think you better do it in
the demo or via blog articles  and in documentation with examples (I know
it is a huge work).

**Comment by rchavik** [comment]
Why would we need public contributions for the main site or the blog at this point?

How would changing the site to static pages help the project or move things forward?

We already have the docs in 'static' files, and so far things are not moving at all. And that's where we actually need public contributions on. Not the main site, nor the blog site.

**Comment by DirtyF** [comment]
Interesting questions. Efforts should me made on documentation before
anything else, you're right.

**Comment by MrZoule** [comment]
We understood that it would help to update main site (redirections, different styles). For 2 static pages, we thought it would be simplier, not for community but for you, not to have to maintain a whole CMS.
It was not meant to imply community in it, but to help you. Sorry if it doesn't.
I don't want to interfere with your choices, do what you think right.

But if I may, here are my suggestions :
- as it is, main site doesn't require a CMS. As Croogo believers, we are though using Wordpress for our own website as it is the best tool to do what we want to do. Are "good" developpers not supposed to use best tool at disposal ?
- I agree with Frank, the best way to prove Croogo's abilities is not to use it for the main website, but to show specific examples, have an updated blog and at least have a demo, wich has been recently updated, good.
- I agree, documentation is top priority. Frank and I could go that way in the future. But some parts are technical and I am affraid not to be able to do the all the thing, especially in english (as you can see...).

So Frank and I did what we technicaly could do to help during our Croogo Hackathon yesterday. I will not get furious if you don't use it, you're the bosses. But think about getting things easier for you, to focus on main priorities.

**Comment by rchavik** [comment]
All,

I decided not to move to static pages.  So, yesterday, I started merging the main site and blog site.  Since around 1 hour ago, production has been running the merged version.

The current themes are in bitbucket and I'll open up the repo for these two themes shortly. However, these two themes will be revamped and unified and I don't expect to further enhance them aside from minor bug fixes. In the future we will create a new theme to replace these, one that hopefully closes #1 

Thank you for your efforts.  I really regret that your work could not be merged, and I hope that this won't deter you from contributing in the future.

**Comment by MrZoule** [comment]
No pb. 
Since our technical skills are limited, Frank and I would like to know everything about your vision on future documentation in order to help out. Can you please write something in a ticket ?

**Pull request closed without merging**
